#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

NumPy is widely used in data analysis tasks, including data cleaning, manipulation, and transformation, due to its efficient array operations and mathematical functionalities.

Applications in physics, biology, engineering, and finance leverage NumPy for simulations, solving differential equations, numerical integration, and more.

NumPy forms the backbone of many machine learning algorithms by handling data representation and mathematical computations efficiently, supporting tasks like feature extraction, data normalization, and model evaluation.

One of the most basic building blocks in the Numpy toolkit is the Numpy N-dimensional array (ndarray), which is used for arrays of between 0 and 32 dimensions (0 meaning a “scalar”).

For example,

matrix 1dis a 1d array, aka a vector, of shape (3,), andmatrix 2dis a 2d array of shape (2, 3).

While arrays are similar to standard Python lists (or nested lists) in some ways, arrays are much faster for lots of array operations.

However, arrays generally have to contain objects of the same type in order to benefit from this increased performance, and usually that means numbers.

In contrast, standard Python lists are very versatile in that each list item can be pretty much any Python object (and different to the other elements), but this versatility comes at the cost of drastically reduced speed.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In the Numpy library, there are two functions np.mean() and np.average() are present. Both are actually doing nearly the same job of calculating mean/average. The difference comes when we are calculating the weighted average. If that is the case then we have to use np.average(). With np.average function we can calculate both arithmetic mean and weighted average.

Difference between np.average() and np.mean()

np.mean()

Use to calculate arithmetic mean
All elements have equal weight
Weight cannot be passed trough the parameter of the given function.
Syntax :

np.mean(arr, axis = None)

where ‘arr’ is the given array.

np.average()

Use to calculate the arithmetic mean as well as weighted average.
All elements may or may not have equal weight.
Weight can be passed through the parameter of the given function.
Syntax :

numpy.average(arr, axis = None, weights = None)

Where ‘arr’ is the given array


3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

   
Reversing a NumPy array can be done in several ways, depending on the axis along which you want to reverse. The following are common methods to reverse an array in NumPy:

Method 1: Using Slicing ([::-1])
This is the simplest and most common way to reverse a NumPy array. You can apply this slicing technique to reverse along any axis.



In [1]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]

print("Original array:", arr_1d)
print("Reversed array:", reversed_1d)


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


In [2]:
# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_2d_rows = arr_2d[::-1, :]

print("Original array:\n", arr_2d)
print("Reversed rows:\n", reversed_2d_rows)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


Method 2: Using np.flip()
NumPy provides the np.flip() function, which allows you to reverse an array along a specific axis. This method is more explicit than slicing.

In [3]:
reversed_1d_flip = np.flip(arr_1d)

print("Reversed array using np.flip():", reversed_1d_flip)


Reversed array using np.flip(): [5 4 3 2 1]


Method 3: Using np.fliplr() and np.flipud()
NumPy has special functions for reversing along specific axes in 2D arrays.

np.fliplr(): Flip an array horizontally (left to right).
np.flipud(): Flip an array vertically (up to down)

In [4]:
reversed_horizontally = np.fliplr(arr_2d)

print("Reversed horizontally:\n", reversed_horizontally)


Reversed horizontally:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

In NumPy, we can determine the data type of the elements stored in an array using the dtype attribute. Each array in NumPy is homogenous, meaning all elements are of the same type, and this type is stored in the dtype attribute of the array object.

For example:

In [5]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype)


int32


Importance of Data Types in Memory Management and Performance
1. Memory Management
The data type of an array directly impacts how much memory is used to store the elements. Different data types allocate different amounts of memory for each element:

Integer types: Typically, int8 uses 1 byte per element, int16 uses 2 bytes, and int64 uses 8 bytes.
Floating-point types: float32 uses 4 bytes, while float64 uses 8 bytes.
Choosing the right data type can lead to significant memory savings, especially when dealing with large datasets. For example, if you only need to store small integers, using int8 can dramatically reduce the memory footprint compared to int64, but this comes at the cost of a reduced range of values.

This is particularly important in applications that deal with large-scale data, such as machine learning, image processing, or big data analytics. Optimizing data types can allow you to process more data in memory at once, reduce storage costs, and minimize the need for memory swaps or out-of-memory errors.

2. Performance
Data types also affect the performance of computations. Smaller data types, like int8 or float32, are processed faster by the CPU because they require less memory bandwidth and allow more data to fit into the CPU cache. This reduces the time spent on memory access and can speed up operations, especially in repetitive or large-scale computations.

Smaller data types can lead to faster computations because they reduce the amount of data processed by the CPU and make better use of memory bandwidth and cache.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

An ndarray (N-dimensional array) is the core data structure of the NumPy library. It is a powerful multi-dimensional container for homogeneous data (all elements of the array are of the same type). NumPy arrays can have any number of dimensions (1D, 2D, 3D, etc.) and are used to efficiently store and perform mathematical operations on large datasets.

Key Features of NumPy ndarrays
Homogeneous Data Type: All elements in an ndarray must have the same data type (e.g., integers, floats, etc.). This contrasts with Python lists, which can hold objects of different types.

Fixed Size: Once a NumPy array is created, its size is fixed. This means you cannot append or remove elements like you can with a Python list. To change the size, you need to create a new array.

N-Dimensional: Unlike Python lists, which are typically 1D, NumPy arrays can have any number of dimensions, making them suitable for representing matrices, tensors, and other complex data structures.

Efficient Memory Usage: ndarrays are memory-efficient because they store elements in contiguous memory blocks. This minimizes overhead compared to Python lists, which are essentially arrays of pointers to objects stored in various locations in memory.

Vectorized Operations: NumPy supports vectorized operations, allowing mathematical operations to be applied directly to entire arrays without the need for explicit loops. This makes operations much faster and more concise.

Data Type (dtype): Each ndarray has a dtype that defines the type of elements stored (e.g., int32, float64). This helps in precise control over memory consumption and performance.


Differences Between ndarrays and Python Lists
Data Type Homogeneity:

Python Lists: Can store elements of different types (e.g., integers, floats, strings).
NumPy ndarrays: All elements must be of the same type, which ensures efficient memory storage and processing.
Performance:

Python Lists: Iterating and performing mathematical operations on Python lists is slower due to the overhead of dynamic typing and storage of objects.
NumPy Arrays: Operations are faster because ndarrays are stored in contiguous memory blocks, enabling efficient access and computation via vectorized operations.
Memory Usage:

Python Lists: Use more memory since they store references to objects rather than the objects themselves.
NumPy Arrays: Use less memory because the elements are stored directly in memory with a fixed type.
Dimensionality:

Python Lists: Are typically 1D (though they can be nested to create multidimensional structures, but inefficiently).
NumPy Arrays: Can be n-dimensional by design (e.g., 2D matrices, 3D tensors), making them more suitable for complex numerical computations.
Mathematical Operations:

Python Lists: Do not natively support element-wise operations. You would need to loop through elements for such operations.
NumPy Arrays: Support element-wise operations directly, making mathematical computations more efficient and concise.
Broadcasting:

Python Lists: Require explicit looping and resizing for operations on differently sized lists.
NumPy Arrays: Can automatically "broadcast" arrays with different shapes for compatible element-wise operations.
Indexing and Slicing:

Python Lists: Support basic indexing and slicing but are limited in multi-dimensional use.
NumPy Arrays: Offer more advanced and efficient slicing and indexing techniques, especially in higher dimensions.



6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
:
1. Memory Efficiency and Contiguous Storage
Python Lists:

Python lists are arrays of pointers, each pointing to a memory location where an object is stored. Each element in the list can be of a different type and size, which introduces memory overhead due to the need for references (pointers) and dynamic typing.
NumPy Arrays:

NumPy arrays store elements in contiguous blocks of memory. All elements are of the same type (dtype), and the array stores the data directly in memory. This makes memory access much faster because the data is stored in adjacent memory locations, and there is no need for pointers.

2. Homogeneous Data Types
Python Lists:

Python lists can store elements of different data types (e.g., integers, strings, floats). The dynamic typing and object storage of each element introduce overhead because each operation must first check the data type and manage the conversion as needed.
NumPy Arrays:

NumPy arrays are strictly homogeneous, meaning all elements must be of the same type. This allows for optimized, low-level, and type-specific implementations of operations, avoiding the overhead of dynamic typing.

3. Vectorized Operations
Python Lists:

Python lists do not natively support element-wise operations. To perform operations like addition or multiplication on the elements of a list, you must explicitly loop through the elements. This manual looping is slow due to Python's inherent overhead for interpreted loops.
NumPy Arrays:

NumPy arrays support vectorized operations, which allow mathematical operations to be applied directly to the entire array without needing explicit loops. This is done using optimized C-level code, which is much faster than Python’s native loops.

4. Broadcasting
Python Lists:

When performing operations between two lists of different sizes or dimensions, you need to manually reshape or loop through the lists to ensure compatibility. This adds extra complexity and computational overhead.
NumPy Arrays:

NumPy arrays support broadcasting, which allows operations to be performed between arrays of different shapes and sizes without explicitly resizing or looping through them. Broadcasting automatically aligns the shapes of the arrays to make them compatible for element-wise operations.

5. Multidimensional Capabilities
Python Lists:

Python lists can be nested to simulate multidimensional arrays (e.g., lists of lists). However, performing operations on multidimensional lists involves complex and inefficient manual loops, making it impractical for large-scale data.
NumPy Arrays:

NumPy natively supports multidimensional arrays (e.g., 2D matrices, 3D tensors) and provides highly optimized operations for these arrays, including slicing, reshaping, and mathematical operations across multiple dimensions.




7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Comparison of vstack() and hstack() in NumPy
The vstack() and hstack() functions in NumPy are used for stacking arrays along different axes:

vstack() (Vertical Stack): Stacks arrays vertically, i.e., row-wise. It adds arrays as new rows, and thus, the number of columns (width) must match.
hstack() (Horizontal Stack): Stacks arrays horizontally, i.e., column-wise. It adds arrays as new columns, and thus, the number of rows (height) must match.
1. vstack() (Vertical Stack)
Purpose: Stacks arrays vertically (along rows).
Requirements: Arrays must have the same number of columns (same width) to be vertically stacked.

In [6]:
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stacking
result_vstack = np.vstack((arr1, arr2))
print(result_vstack)


[[1 2 3]
 [4 5 6]]


In [7]:
#2. hstack() (Horizontal Stack)
#Purpose: Stacks arrays horizontally (along columns).
#Requirements: Arrays must have the same number of rows (same height) to be horizontally stacked.


# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontal stacking
result_hstack = np.hstack((arr1, arr2))
print(result_hstack)


[1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Differences Between fliplr() and flipud() in NumPy
Both fliplr() and flipud() are functions in NumPy used to reverse the order of elements in an array. However, they operate along different axes, which leads to different effects on the array structure.

1. fliplr() (Flip Left to Right)
Purpose: Flips the array horizontally by reversing the order of columns, i.e., it mirrors the array along the vertical axis.
Effect: This function is only applicable to arrays with 2 or more dimensions. It reverses the order of columns while keeping the rows unchanged.


In [9]:
#Example with a 2D array:

import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Flip the array left to right (horizontally)
result_fliplr = np.fliplr(arr)
print(result_fliplr)


[[3 2 1]
 [6 5 4]]


In [10]:
#2. flipud() (Flip Up to Down)
#Purpose: Flips the array vertically by reversing the order of rows, i.e., it mirrors the array along the horizontal axis.
#Effect: It reverses the order of rows in the array while keeping the columns unchanged. Unlike fliplr(), this function works for both 1D and higher-dimensional arrays.

#Example with a 3D array:
#For higher-dimensional arrays, flipud() flips along the first axis (the row axis), leaving other axes untouched.

arr_3d = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])

# Flip the 3D array along the rows
result_flipud_3d = np.flipud(arr_3d)
print(result_flipud_3d)


[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?


The array_split() method in NumPy is used to split an array into multiple sub-arrays. Unlike the split() function, which requires the number of splits to divide the array evenly, array_split() can handle uneven splits. This flexibility makes array_split() more versatile when dealing with arrays that may not be perfectly divisible by the number of splits.

Functionality
Purpose: To split an array into sub-arrays. If the array cannot be split evenly, array_split() handles the remainder by distributing extra elements across some sub-arrays.
Parameters:
array: The input array to be split.
indices_or_sections: Either the number of equal parts to split the array into or a list of indices where the split should happen.
Return Value: A list of sub-arrays.


Handling Uneven Splits
When the array size is not evenly divisible by the number of splits, array_split() divides the elements as evenly as possible. It ensures that sub-arrays get as close as possible to equal size. The remaining elements are distributed such that the first few sub-arrays are slightly larger than the others.

In [11]:
#Example of Uneven Split:
#Consider an array with 7 elements, and you want to split it into 3 parts.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
result = np.array_split(arr, 3)
print(result)


[array([1, 2, 3]), array([4, 5]), array([6, 7])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

The concept of vectorized operations on NumPy allows the use of more optimal and pre-compiled functions and mathematical operations on NumPy array objects and data sequences. The Output and Operations will speed up when compared to simple non-vectorized operations.   

In [12]:
#Using vectorized sum method on NumPy array. We will compare the vectorized sum method along with simple non-vectorized operation i.e the iterative method to calculate the sum of numbers from 0 – 14,999.


# importing the modules
import numpy as np
import timeit
 
# vectorized sum
print(np.sum(np.arange(15000)))
 
print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(np.arange(15000))
 
# iterative sum
total = 0
for item in range(0, 15000):
    total += item
a = total
print("\n" + str(a))
 
print("Time taken by iterative sum : ", end = "")
%timeit a

112492500
Time taken by vectorized sum : 19.4 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

112492500
Time taken by iterative sum : 18.3 ns ± 0.807 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language.

It does this without making needless copies of data which leads to efficient algorithm implementations. But broadcasting over multiple arrays in NumPy extension can raise cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows down the computation.

The resulting array returned after broadcasting will have the same number of dimensions as the array with the greatest number of dimensions.

In [16]:

import numpy as np 
a = np.array([17, 11, 19]) # 1x3 Dimension array 
print(a) 
b = 3  
print(b) 
  
# Broadcasting happened because of 
# miss match in array Dimension. 
c = a + b  
print(c)

[17 11 19]
3
[20 14 22]


Practical Questions:

In [17]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns

import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Step 2: Interchange rows and columns
transposed_array = np.transpose(array)
# Alternatively, you can use array.T to achieve the same result
# transposed_array = array.T

print("\nTransposed Array (Interchanged Rows and Columns):")
print(transposed_array)


Original Array:
[[56 32 64]
 [77 96 83]
 [21 74 22]]

Transposed Array (Interchanged Rows and Columns):
[[56 77 21]
 [32 96 74]
 [64 83 22]]


In [18]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)  # Alternatively, use np.random.randint(1, 101, size=10)
print("Original 1D Array:")
print(array_1d)

# Step 2: Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape((2, 5))
print("\nReshaped 2x5 Array:")
print(array_2x5)

# Step 3: Reshape the array into a 5x2 array
array_5x2 = array_1d.reshape((5, 2))
print("\nReshaped 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Step 2: Add a border of zeros around the array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(array_6x6)


Original 4x4 Array:
[[0.10111446 0.32188647 0.75185619 0.93966785]
 [0.8624976  0.06825311 0.19710511 0.29324764]
 [0.55812116 0.06694055 0.82658863 0.66008163]
 [0.76422623 0.76152662 0.72670696 0.02719128]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.10111446 0.32188647 0.75185619 0.93966785 0.        ]
 [0.         0.8624976  0.06825311 0.19710511 0.29324764 0.        ]
 [0.         0.55812116 0.06694055 0.82658863 0.66008163 0.        ]
 [0.         0.76422623 0.76152662 0.72670696 0.02719128 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [20]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)  # The stop value is 65 to include 60
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


In [21]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Step 1: Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply uppercase transformation
uppercase_array = np.char.upper(string_array)
print("Uppercase:")
print(uppercase_array)

# Step 3: Apply lowercase transformation
lowercase_array = np.char.lower(string_array)
print("\nLowercase:")
print(lowercase_array)

# Step 4: Apply title case transformation
titlecase_array = np.char.title(string_array)
print("\nTitle Case:")
print(titlecase_array)



Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']


In [22]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array

import numpy as np

# Step 1: Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)
print("Words with spaces between characters:")
print(spaced_words_array)


Words with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [23]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Step 2: Perform element-wise addition
addition = array1 + array2
print("Element-wise Addition:")
print(addition)

# Step 3: Perform element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Step 4: Perform element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Step 5: Perform element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)


Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [24]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [25]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
array = np.random.randint(0, 1001, size=100)
print("Generated Array:")
print(array)

# Step 2: Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Find and display all prime numbers in the array
prime_numbers = np.array([num for num in array if is_prime(num)])
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Generated Array:
[920 845 329 951 605 782 428  31 144 633 233 621 405 940 236 145 285 574
 229 295 186 125 372 993 137 505 868 949 114 139 888 248 260 498 171  77
 578 146 927 962 677 541 577 781 454  28 592  30 134 353 922 370 946 734
 541 442 364 741 411 426 845 937 611 366 409 614 877 670 872 568 576 996
 850 386 559 802  82 835 521 313 436 594 661 978 728  17  26  67 767 982
 104 366 213 417  39 202 703  59 423 584]

Prime Numbers in the Array:
[ 31 233 229 137 139 677 541 577 353 541 937 409 877 521 313 661  17  67
  59]


In [28]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.



# Generate a NumPy array of daily temperatures for a month (30 days)
np.random.seed(0)  # For reproducibility
daily_temperatures = np.random.uniform(0, 35, size=30)
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into 5 weeks of 6 days each
weekly_temperatures = daily_temperatures.reshape(5, 6)
print("\nWeekly Temperatures (5 weeks of 6 days):")
print(weekly_temperatures)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Averages:")
print(weekly_averages)

# Additional calculations
highest_temp = np.max(daily_temperatures)
lowest_temp = np.min(daily_temperatures)
monthly_average = np.mean(daily_temperatures)
temperature_ranges = np.ptp(weekly_temperatures, axis=1)  # Peak-to-peak (range)

print(f"\nHighest Temperature of the Month: {highest_temp:.2f}°C")
print(f"Lowest Temperature of the Month: {lowest_temp:.2f}°C")
print(f"\nOverall Monthly Average Temperature: {monthly_average:.2f}°C")
print("\nTemperature Ranges for Each Week:")
print(temperature_ranges)




Daily Temperatures for the Month:
[19.20847264 25.03162782 21.09671816 19.0709114  14.82791798 22.60629396
 15.31555239 31.21205503 33.72819662 13.42045316 27.71037633 18.51132219
 19.88155964 32.39588234  2.48626204  3.04952549  0.70764391 29.14169459
 27.23548628 30.45042519 34.25164198 27.97054975 16.15177768 27.31852117
  4.13960491 22.39723575  5.01736506 33.0634121  18.26469126 14.5131679 ]

Weekly Temperatures (5 weeks of 6 days):
[[19.20847264 25.03162782 21.09671816 19.0709114  14.82791798 22.60629396]
 [15.31555239 31.21205503 33.72819662 13.42045316 27.71037633 18.51132219]
 [19.88155964 32.39588234  2.48626204  3.04952549  0.70764391 29.14169459]
 [27.23548628 30.45042519 34.25164198 27.97054975 16.15177768 27.31852117]
 [ 4.13960491 22.39723575  5.01736506 33.0634121  18.26469126 14.5131679 ]]

Weekly Averages:
[20.30699033 23.31632595 14.610428   27.22973367 16.23257949]

Highest Temperature of the Month: 34.25°C
Lowest Temperature of the Month: 0.71°C

Overall Monthly Av